name = "junedang-blog"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_date = "2026-02-18"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".svelte-kit/cloudflare"
binding = "ASSETS"

[vars]
PUBLIC_MAINTENANCE_MODE = "false"
GITHUB_PAGE_URL="https://jimmy706.github.io"
GITHUB_BLOG_APP="junedang-blog-pages"
[observability]
[observability.logs]
enabled = true
invocation_logs = true